Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,13 +3,12 @@ name: Build one-hub
 on: workflow_dispatch
 
 jobs:
-  test:
+  build:
     runs-on: ubuntu-latest
     name: Build one-hub
     steps:
     
-      - uses: actions/checkout@v4
-    
+      : actions/checkout@v4
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
@@ -17,8 +16,8 @@ jobs:
 
       - name: Clone Repo
         run: |
-            export=$(wget -qO- https://api.github.com/repos/MartialBE/one-hub/tags | gawk -F '["v]' '/name/{print "v"$$5;exit}')
-            git clone -b $LATEST_APP https://github.com/MartialBE/one-hub
+            export LATEST_TAG=$(wget -qO- https://api.github.com/repos/MartialBE/one-hub/tags | gawk -F '["v]' '/name/{print $4;exit}')
+            git clone -b v$$LATEST_TAG https://github.com/MartialBE/one-hub
 
       - name: Build Frontend
         env:
@@ -27,24 +26,25 @@ jobs:
           cd one-hub/web
           npm install
           REACT_APP_VERSION=$(git describe --tags) npm run build
-          cd ../..
+          c..
 
       - name: Build Backend
-        /freebsd-vm@v1
+        uses: vmactions/freebsd-vm@v1
         with:
           usesh: true
           release: 13.2
           prepare: |
             pkg install -y jq wget curl git gcc bash gawk gsed
-            wget https://dl.google.com/go/go1.22.0.freebs.tar.gz && tar -C /usr/local -xzf go1.22.0.freebsd-amd64.tar go1.22.0.freebsd-amd64.tar.gz
-            usr/local/go/bin/go /usr/local/bin/go
+            wget https://dl.google.com/go/go1.22.0.freebsd-amd64.tar.gz && tar -C /usr/local -xzf go1.22.0.freebsd-amd64.tar.gz && rm go1.22.0.freebsd-amd64.tar.gz
+            ln -s /usr/local/go/bin/go /usr/local/bin/go
           run: |
             git config --global --add safe.directory /home/runner/work/one-hub-freebsd/one-hub-freebsd/one-hub
-            cd one- mod download
-            go build -ldflags "-s -w -X 'main describe --tags)' -extldflags '-static'" -o one-hub
+            cd one-hub
+            go mod download
+            go build -ldflags "-s -w -X 'main.Version=$(git describe --tags)' -extldflags '-static'" -o one-hub || (echo "Build failed"; exit 1)
 
       - name: Upload artifact
-        usesd-artifact@main
+        uses: actions/upload-artifact@main
         with:
           name: one-hub-freebsd
           path: |
@@ -52,10 +52,11 @@ jobs:
   
       - name: Generate release tag
         id: tag
-        run: echo "release_tag=$(wget -qO- https://api.github.com/repos/MartialBE/one-hub/tags | gawk -F '["v]' '/name/{print5;exit}')" >> $GITHUB_OUTPUT
+        run: echo "release_tag=$(wget -qO- https://api.github.com/ialBE/one-hub/tags | gawk -F '["v]' '/name/{print $4;exit}')" >> $GITHUB_OUTPUT
 
       - name: Create release
-        uses: softprops/action-env:
+        uses: softprops/action-gh-release@v1
+        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ steps.tag.outputs.release_tag }}
@@ -66,6 +67,5 @@ jobs:
         uses: Mattraks/delete-workflow-runs@v2
         with:
           token: ${{ github.token }}
-          repository: ${{ github.repository }}
-          retain_days: 1
+          repository: ${{ github.repository_days: 1
           keep_minimum_runs: 8
